import Topbar from "../DashboardLogged/Topbar";
import React, { useState, useEffect, useRef } from 'react';
import DashboardLayout from '../DashboardLogged/DashboardLayout';
import './CareerOrientation.css';
import { BarChart as IconChart, Briefcase as IconBriefcase, Cloud as IconCloud } from "lucide-react";

// Import FontAwesome Icons
import {
  FaWandMagicSparkles,
  FaChartLine,
  FaBriefcase,
  FaCloud,
  FaArrowTrendUp,
  FaRightLeft,
  FaCommentDots,
  FaCircleCheck,
  FaPaperPlane,
  FaLightbulb
} from "react-icons/fa6";

export default function CareerOrientation() {
  const [activeTab, setActiveTab] = useState('side-by-side');
  const [compareIndex, setCompareIndex] = useState(0);
  const [inputVal, setInputVal] = useState('');
  const messagesEndRef = useRef(null);

  // ── API state ──────────────────────────────────────────────
  const [careers, setCareers] = useState([]);
  const [loading, setLoading] = useState(true);

  // Icon + style map dựa theo thứ tự vị trí
  const CAREER_ICONS = [<IconChart />, <IconBriefcase />, <IconCloud />];
  const CAREER_ICON_CLS = ['blue', 'green', 'purple'];
  const CAREER_LVL_MAP = { high: { label: 'Rất cao', cls: 'green' }, medium: { label: 'Cao', cls: 'blue' }, low: { label: 'Trung bình', cls: 'orange' } };
  const CAREER_BADGE = ['AI gợi ý', 'Hot Trend', null];
  const CAREER_BADGE_CLS = ['blue', 'green', null];

  const fetchCareers = () => {
    const user = JSON.parse(localStorage.getItem('career_user'));
    const userId = user ? user.user_id : 19;
    setLoading(true);
    fetch(`http://localhost:5000/api/career/${userId}`)
      .then(r => r.json())
      .then(json => {
        if (!json.success) throw new Error(json.message);
        const mapped = json.data.map((c, i) => {
          const pct = Math.round(c.match_percentage);
          const lvlKey = pct >= 90 ? 'high' : pct >= 80 ? 'medium' : 'low';
          let parsedSkills = [];
          try {
            parsedSkills = c.skills ? JSON.parse(c.skills) : [];
          } catch(e) {}
          
          return {
            title: c.job_title,
            match: pct,
            level: CAREER_LVL_MAP[lvlKey].label,
            levelClass: CAREER_LVL_MAP[lvlKey].cls,
            desc: c.job_description || '',
            skills: parsedSkills,
            salary: c.salary || 'Đang cập nhật',
            potential: c.potential || (pct / 10).toFixed(1),
            trend_analysis: c.trend_analysis || '',
            badge: CAREER_BADGE[i] || null,
            badgeClass: CAREER_BADGE_CLS[i] || null,
            icon: CAREER_ICONS[i] || <IconBriefcase />,
            iconClass: CAREER_ICON_CLS[i] || 'blue',
          };
        });
        setCareers(mapped);
      })
      .catch(() => { })
      .finally(() => setLoading(false));
  };

  const generateCareers = async () => {
    const user = JSON.parse(localStorage.getItem('career_user'));
    const userId = user ? user.user_id : 19;
    setLoading(true);
    try {
      // Lấy kỹ năng từ portfolio (userskill table)
      let portfolioSkills = [];
      try {
        const skillsRes = await fetch(`http://localhost:5000/api/skills/${userId}`);
        const skillsJson = await skillsRes.json();
        if (skillsJson.success) portfolioSkills = skillsJson.data.map(s => s.skill_name);
      } catch {}

      const res = await fetch('http://localhost:5000/api/career/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: userId, portfolio_skills: portfolioSkills })
      });
      await res.json();
      fetchCareers();
    } catch (e) {
      console.error(e);
      setLoading(false);
    }
  };

  // Load careers on mount
  useEffect(() => {
    fetchCareers();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Auto-generate khi chưa có gợi ý (sau khi fetch xong và careers vẫn rỗng)
  const autoGeneratedRef = React.useRef(false);
  useEffect(() => {
    if (!loading && careers.length === 0 && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      generateCareers();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, careers.length]);

  // Comparison role options (toggled with the Swap button)
  const comparisonPairs = careers.length >= 2 ? [
    {
      left: {
        title: careers[0].title,
        badge: careers[0].badge || "Lựa chọn tốt nhất",
        badgeClass: careers[0].badgeClass || "blue",
        skills: careers[0].skills?.length ? careers[0].skills : ["Tư duy phân tích", "Chuyên môn sâu"],
        salary: careers[0].salary !== 'Đang cập nhật' ? careers[0].salary : "15M - 35M",
        potential: careers[0].potential,
        pct: careers[0].match,
        colorClass: careers[0].iconClass || "blue",
        trend_analysis: careers[0].trend_analysis || "Đang có xu hướng tăng trưởng cực kỳ mạnh mẽ."
      },
      right: {
        title: careers[1].title,
        badge: careers[1].badge || "Phù hợp cao",
        badgeClass: careers[1].badgeClass || "green",
        skills: careers[1].skills?.length ? careers[1].skills : ["Tư duy hệ thống", "Giải quyết vấn đề"],
        salary: careers[1].salary !== 'Đang cập nhật' ? careers[1].salary : "12M - 30M",
        potential: careers[1].potential,
        pct: careers[1].match,
        colorClass: careers[1].iconClass || "teal",
        trend_analysis: careers[1].trend_analysis || "Nhu cầu luôn ổn định ở mức cao."
      }
    },
    careers.length >= 3 ? {
      left: {
        title: careers[1].title,
        badge: careers[1].badge || "Phù hợp cao",
        badgeClass: careers[1].badgeClass || "green",
        skills: careers[1].skills?.length ? careers[1].skills : ["Tư duy hệ thống", "Giải quyết vấn đề"],
        salary: careers[1].salary !== 'Đang cập nhật' ? careers[1].salary : "12M - 30M",
        potential: careers[1].potential,
        pct: careers[1].match,
        colorClass: careers[1].iconClass || "green",
        trend_analysis: careers[1].trend_analysis || "Nhu cầu luôn ổn định ở mức cao."
      },
      right: {
        title: careers[2].title,
        badge: careers[2].badge || "Đang phát triển",
        badgeClass: careers[2].badgeClass || "purple",
        skills: careers[2].skills?.length ? careers[2].skills : ["Nghiên cứu", "Tư duy sáng tạo"],
        salary: careers[2].salary !== 'Đang cập nhật' ? careers[2].salary : "10M - 25M",
        potential: careers[2].potential,
        pct: careers[2].match,
        colorClass: careers[2].iconClass || "purple",
        trend_analysis: careers[2].trend_analysis || "Có tiềm năng phát triển trong tương lai."
      }
    } : null
  ].filter(Boolean) : [
    {
      left: { title: "Đang tải...", badge: "...", badgeClass: "blue", skills: [], salary: "...", potential: 0, pct: 0, colorClass: "blue", trend_analysis: "" },
      right: { title: "Đang tải...", badge: "...", badgeClass: "green", skills: [], salary: "...", potential: 0, pct: 0, colorClass: "teal", trend_analysis: "" }
    }
  ];

  const currentPair = comparisonPairs[compareIndex];

  // VN Market Trends
  const trends = [
    { num: "01", name: "Generative AI", change: "+ 24%" },
    { num: "02", name: "Cloud Native", change: "+ 18%" },
    { num: "03", name: "Cyber Security", change: "+ 15%" }
  ];

  // Chat message simulation state
  const [messages, setMessages] = useState([
    {
      id: 1,
      sender: 'assistant',
      text: 'Tuyệt vời! Tôi đã xem qua CV của bạn. Với nền tảng Toán học siêu "đỉnh" này, bạn đang có lợi thế cực lớn đấy! Bạn muốn tôi tư vấn sâu hơn về Data Analyst hay vị trí nào khác không?'
    },
    {
      id: 2,
      sender: 'user',
      text: 'Tôi đang phân vân giữa Data Analyst và Business Analyst. Vị trí nào sẽ khai thác tốt nhất kỹ năng Python của tôi?'
    },
    {
      id: 3,
      sender: 'assistant',
      isAnalyzing: true
    }
  ]);

  // Handle auto-completion of the initial loading state
  useEffect(() => {
    const timer = setTimeout(() => {
      setMessages(prev => prev.map(m => m.isAnalyzing ? {
        id: 3,
        sender: 'assistant',
        text: 'Cả hai vai trò đều rất tiềm năng! Tuy nhiên, Data Analyst sẽ khai thác kỹ năng Python của bạn chuyên sâu hơn. Bạn sẽ sử dụng Python hàng ngày để xử lý dữ liệu (Pandas, NumPy), xây dựng mô hình dự báo và trực quan hóa dữ liệu. Trong khi đó, Business Analyst tập trung nhiều hơn vào quy trình nghiệp vụ và ít code trực tiếp hơn.'
      } : m));
    }, 1500);
    return () => clearTimeout(timer);
  }, []);

  // Auto-scroll chat to bottom when messages update
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Handle custom text submit
  const handleSendText = async (text) => {
    if (!text.trim()) return;

    const userMsgId = Date.now();
    const newUserMsg = { id: userMsgId, role: 'user', sender: 'user', text, content: text };
    const loadingMsgId = userMsgId + 1;
    const newLoadingMsg = { id: loadingMsgId, sender: 'assistant', isAnalyzing: true };

    const newMessages = [...messages, newUserMsg];
    setMessages([...newMessages, newLoadingMsg]);
    setInputVal('');

    try {
      const res = await fetch('http://localhost:5000/api/career/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: newMessages })
      });
      const json = await res.json();
      if (json.success) {
        setMessages(prev => prev.map(m => m.id === loadingMsgId ? {
          id: loadingMsgId,
          role: 'assistant',
          sender: 'assistant',
          text: json.data,
          content: json.data
        } : m));
      } else {
        setMessages(prev => prev.map(m => m.id === loadingMsgId ? {
          id: loadingMsgId,
          role: 'assistant',
          sender: 'assistant',
          text: "Xin lỗi, hiện tại tôi không thể trả lời. Vui lòng thử lại sau.",
          content: "Xin lỗi, hiện tại tôi không thể trả lời. Vui lòng thử lại sau."
        } : m));
      }
    } catch (e) {
      setMessages(prev => prev.map(m => m.id === loadingMsgId ? {
        id: loadingMsgId,
        role: 'assistant',
        sender: 'assistant',
        text: "Xin lỗi, đã xảy ra lỗi kết nối.",
        content: "Xin lỗi, đã xảy ra lỗi kết nối."
      } : m));
    }
  };

  const handleSwapRoles = () => {
    setCompareIndex(prev => {
      const nextIndex = (prev + 1) % comparisonPairs.length;
      return Number.isNaN(nextIndex) ? 0 : nextIndex;
    });
  };

  const renderMessageText = (text) => {
    if (!text) return null;
    const lines = text.split('\n');
    return lines.map((line, i) => {
      const parts = line.split(/(\*\*.*?\*\*)/g);
      const renderedLine = parts.map((part, j) => {
        if (part.startsWith('**') && part.endsWith('**')) {
          return <strong key={j}>{part.slice(2, -2)}</strong>;
        }
        return part;
      });
      return (
        <React.Fragment key={i}>
          {renderedLine}
          {i < lines.length - 1 && <br />}
        </React.Fragment>
      );
    });
  };

  return (
    <DashboardLayout>

      <div className="co-page">
        {/* ================= SECTION 1: RECOMMENDATIONS ================= */}
        <div>
          <div className="co-section-header">
            <div className="co-section-title-wrapper">
              <FaWandMagicSparkles className="co-section-icon" />
              <h2 className="co-section-title">Đề xuất Nghề nghiệp Phù hợp</h2>
            </div>
            <button className="co-btn-outline" onClick={generateCareers} disabled={loading} style={{
              background: 'white', border: '1px solid #d1d5db', padding: '6px 12px', borderRadius: '6px', fontSize: '13px', cursor: 'pointer'
            }}>
              {loading ? "Đang tạo..." : "Phân tích bằng AI"}
            </button>
          </div>

          <div className="co-career-grid">
            {loading && (
              <div style={{ gridColumn: '1/-1', textAlign: 'center', padding: '40px', color: '#6b7280', fontSize: '14px' }}>
                Đang tải dữ liệu nghề nghiệp...
              </div>
            )}
            {!loading && careers.map((career, i) => (
              <div key={i} className="co-career-card">
                <div className="co-card-top">
                  <div className={`co-card-icon-container ${career.iconClass}`}>
                    {career.icon}
                  </div>
                  {career.badge && (
                    <span className={`co-card-badge ${career.badgeClass}`}>
                      {career.badge}
                    </span>
                  )}
                </div>

                <h3 className="co-card-title">{career.title}</h3>
                <p className="co-card-desc">{career.desc}</p>

                <div className="co-card-stats">
                  <div className="co-card-stat-col">
                    <p className="co-card-stat-label">ĐỘ PHÙ HỢP</p>
                    <p className="co-card-stat-val green">{career.match}%</p>
                  </div>
                  <div className="co-card-stat-col">
                    <p className="co-card-stat-label">NHU CẦU</p>
                    <p className={`co-card-stat-val ${career.levelClass === 'green' ? 'green' : career.levelClass === 'blue' ? 'blue' : 'orange'}`}>
                      {career.level}
                    </p>
                  </div>
                </div>

                <div className="co-card-tags">
                  {career.skills.map((skill, sIdx) => (
                    <span key={sIdx} className="co-tag">{skill}</span>
                  ))}
                </div>

                <button className="co-card-btn" onClick={() => {
                  window.location.href = `/learning-path?target=${encodeURIComponent(career.title)}`;
                }}>Chi tiết lộ trình học tập</button>
              </div>
            ))}
          </div>
        </div>

        {/* ================= SECTION 2: COMPARISON & TRENDS ================= */}
        <div className="co-two-column-row">
          {/* Compare Card */}
          <div className="co-box-card">
            <div className="co-section-header">
              <div className="co-section-title-wrapper">
                <FaWandMagicSparkles className="co-section-icon" />
                <h2 className="co-section-title">So sánh Nghề nghiệp</h2>
              </div>
              <div className="co-tabs-container">
                <button
                  className={`co-tab-btn ${activeTab === 'side-by-side' ? 'active' : ''}`}
                  onClick={() => setActiveTab('side-by-side')}
                >
                  Side-by-side
                </button>
                <button
                  className={`co-tab-btn ${activeTab === 'deep-analysis' ? 'active' : ''}`}
                  onClick={() => setActiveTab('deep-analysis')}
                >
                  Phân tích sâu
                </button>
              </div>
            </div>

            {activeTab === 'side-by-side' ? (
              <>
                <div className="co-comparison-wrapper">
                  {/* Left Role Column */}
                  <div className="co-compare-col highlighted">
                    <div className="co-compare-header">
                      <div className="co-card-icon-container blue" style={{ width: '32px', height: '32px' }}>
                        <FaChartLine />
                      </div>
                      <div>
                        <h3 className="co-compare-title">{currentPair.left.title}</h3>
                        <span className={`co-compare-badge ${currentPair.left.badgeClass}`}>
                          {currentPair.left.badge}
                        </span>
                      </div>
                    </div>

                    <div className="co-compare-section">
                      <p className="co-compare-sec-label">KỸ NĂNG YÊU CẦU</p>
                      <div className="co-compare-skills-list">
                        {currentPair.left.skills.map((s, idx) => (
                          <span key={idx} className="co-compare-skill-item">{s}</span>
                        ))}
                      </div>
                    </div>

                    <div className="co-compare-section">
                      <p className="co-compare-sec-label">MỨC LƯƠNG TB (VN)</p>
                      <p className="co-compare-salary">{currentPair.left.salary} <span>VND</span></p>
                    </div>

                    <div className="co-compare-section" style={{ borderBottom: 'none', paddingBottom: '0' }}>
                      <p className="co-compare-sec-label">TIỀM NĂNG</p>
                      <div className="co-potential-bar-wrapper">
                        <div className="co-potential-bar-track">
                          <div
                            className={`co-potential-bar-fill ${currentPair.left.colorClass}`}
                            style={{ width: `${currentPair.left.pct}%` }}
                          />
                        </div>
                        <p className="co-potential-val">{currentPair.left.potential}/10</p>
                      </div>
                    </div>
                  </div>

                  {/* Right Role Column */}
                  <div className="co-compare-col">
                    <div className="co-compare-header">
                      <div className="co-card-icon-container green" style={{ width: '32px', height: '32px' }}>
                        <FaBriefcase />
                      </div>
                      <div>
                        <h3 className="co-compare-title">{currentPair.right.title}</h3>
                        <span className={`co-compare-badge ${currentPair.right.badgeClass}`}>
                          {currentPair.right.badge}
                        </span>
                      </div>
                    </div>

                    <div className="co-compare-section">
                      <p className="co-compare-sec-label">KỸ NĂNG YÊU CẦU</p>
                      <div className="co-compare-skills-list">
                        {currentPair.right.skills.map((s, idx) => (
                          <span key={idx} className="co-compare-skill-item">{s}</span>
                        ))}
                      </div>
                    </div>

                    <div className="co-compare-section">
                      <p className="co-compare-sec-label">MỨC LƯƠNG TB (VN)</p>
                      <p className="co-compare-salary">{currentPair.right.salary} <span>VND</span></p>
                    </div>

                    <div className="co-compare-section" style={{ borderBottom: 'none', paddingBottom: '0' }}>
                      <p className="co-compare-sec-label">TIỀM NĂNG</p>
                      <div className="co-potential-bar-wrapper">
                        <div className="co-potential-bar-track">
                          <div
                            className={`co-potential-bar-fill ${currentPair.right.colorClass === 'blue' ? 'blue' : 'teal'}`}
                            style={{ width: `${currentPair.right.pct}%` }}
                          />
                        </div>
                        <p className="co-potential-val">{currentPair.right.potential}/10</p>
                      </div>
                    </div>
                  </div>
                </div>

                <button className="co-compare-swap-btn" onClick={handleSwapRoles}>
                  <FaRightLeft style={{ marginRight: '6px' }} />
                  Thay đổi vai trò so sánh
                </button>
              </>
            ) : (
              <div className="co-deep-analysis">
                <div className="co-da-header">
                  <FaWandMagicSparkles style={{ color: 'var(--primary-color, #3b5bdb)', fontSize: 18 }} />
                  <h4 style={{ margin: 0, color: '#111827', fontSize: 15 }}>Phân tích AI: {currentPair.left.title} vs {currentPair.right.title}</h4>
                </div>
                
                <div className="co-da-content">
                  <div className="co-da-block">
                    <p className="co-da-label">Tương lai & Xu hướng</p>
                    <p className="co-da-text">
                      <strong>{currentPair.left.title}:</strong> {currentPair.left.trend_analysis}
                      <br /><br />
                      <strong>{currentPair.right.title}:</strong> {currentPair.right.trend_analysis}
                    </p>
                  </div>

                  <div className="co-da-block">
                    <p className="co-da-label">Khoảng cách kỹ năng hiện tại</p>
                    <p className="co-da-text">
                      Bạn đang có lợi thế mạnh về tư duy phân tích, đây là gốc rễ của cả 2 mảng. Tuy nhiên, nếu chọn <strong>{currentPair.left.title}</strong>, bạn cần học sâu hơn về công cụ kỹ thuật (SQL, Python). Còn với <strong>{currentPair.right.title}</strong>, bạn nên trau dồi khả năng thuyết trình, quản lý dự án (Agile/Scrum) và thiết kế hệ thống.
                    </p>
                  </div>
                  
                  <div className="co-da-block" style={{ border: 'none', paddingBottom: 0, marginBottom: 0 }}>
                    <p className="co-da-label">AI Khuyến nghị cho bạn</p>
                    <p className="co-da-text" style={{ color: 'var(--primary-color, #3b5bdb)', fontWeight: 500 }}>
                      Dựa trên Bio của bạn, {currentPair.left.title} có vẻ là lựa chọn phù hợp nhất với quỹ đạo phát triển ngắn hạn. Bạn có thể đạt mức năng lực chuyên môn sau khoảng 3 - 6 tháng học tập cường độ cao.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Right column: Trends & Tip */}
          <div className="co-right-col">
            <div className="co-box-card" style={{ flex: '1' }}>
              <div className="co-section-header" style={{ marginBottom: '4px' }}>
                <div className="co-section-title-wrapper">
                  <FaArrowTrendUp className="co-section-icon" />
                  <h2 className="co-section-title">Xu hướng tại VN</h2>
                </div>
              </div>
              <p className="co-trend-subtitle">Kỹ năng tăng trưởng mạnh nhất quý</p>

              <div className="co-trend-list">
                {trends.map((t, idx) => (
                  <div key={idx} className="co-trend-item">
                    <div className="co-trend-left">
                      <span className="co-trend-num">{t.num}</span>
                      <span className="co-trend-name">{t.name}</span>
                    </div>
                    <span className="co-trend-pct">{t.change}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* AI Tip Card */}
            <div className="co-tip-card">
              <div className="co-tip-header">
                <div className="co-tip-title-row">
                  <FaWandMagicSparkles />
                  <span>AI Tip</span>
                </div>
                <span className="co-tip-badge">Gợi ý</span>
              </div>
              <p className="co-tip-content">
                Học thêm <strong>Prompt Engineering</strong> có thể tăng <strong>15%</strong> khả năng được tuyển dụng cho vị trí Data Analyst.
              </p>
            </div>
          </div>
        </div>

        {/* ================= SECTION 3: AI CHATBOT ================= */}
        <div className="co-chat-card">
          {/* Left panel */}
          <div className="co-chat-left-panel">
            <div className="co-chat-intro">
              <div className="co-chat-icon-container">
                <FaCommentDots style={{ fontSize: '20px' }} />
              </div>
              <h3 className="co-chat-title">Trò chuyện cùng Chuyên gia AI</h3>
              <p className="co-chat-subtitle">
                Tôi là trợ lý ảo đầy năng lượng của bạn. Hãy hỏi tôi bất cứ điều gì về lộ trình sự nghiệp nhé.
              </p>
            </div>

            <div className="co-chat-quick-section">
              <span className="co-chat-quick-label">Vẫn chưa bắt đầu?</span>
              <button
                className="co-chat-quick-btn"
                onClick={() => handleSendText("Làm sao để lên Senior DA trong 2 năm?")}
              >
                Làm sao để lên Senior DA trong 2 năm?
              </button>
              <button
                className="co-chat-quick-btn"
                onClick={() => handleSendText("Chứng chỉ AI nào giá trị nhất hiện nay?")}
              >
                Chứng chỉ AI nào giá trị nhất hiện nay?
              </button>
            </div>
          </div>

          {/* Right chat window */}
          <div className="co-chat-window">
            <div className="co-chat-messages-container">
              {messages.map((m, idx) => (
                <div key={m.id || idx} className={`co-msg-row ${m.sender === 'assistant' ? 'assistant' : 'user'}`}>
                  <div className={`co-chat-avatar ${m.sender === 'assistant' ? 'assistant' : 'user'}`}>
                    {m.sender === 'assistant' ? '🤖' : 'NA'}
                  </div>
                  <div className="co-msg-content-wrapper">
                    <span className="co-msg-sender-name">
                      {m.sender === 'assistant' ? 'Assistant' : (() => { try { return JSON.parse(localStorage.getItem('career_user'))?.full_name?.split(' ').pop() || 'Bạn'; } catch { return 'Bạn'; } })()}
                      {m.sender === 'assistant' && (
                        <span className="co-verif-badge">
                          <FaCircleCheck />
                        </span>
                      )}
                    </span>

                    {m.isAnalyzing ? (
                      <div className="co-chat-bubble analyzing">
                        <span>ĐANG PHÂN TÍCH</span>
                        <span className="co-dot-flashing"></span>
                      </div>
                    ) : (
                      <div className={`co-chat-bubble ${m.sender === 'assistant' ? 'assistant' : 'user'}`}>
                        {renderMessageText(m.text)}
                      </div>
                    )}
                  </div>
                </div>
              ))}
              <div ref={messagesEndRef} />
            </div>

            <form
              className="co-chat-input-bar"
              onSubmit={(e) => {
                e.preventDefault();
                handleSendText(inputVal);
              }}
            >
              <input
                type="text"
                className="co-chat-input-field"
                placeholder="Hỏi tôi về lộ trình của bạn..."
                value={inputVal}
                onChange={(e) => setInputVal(e.target.value)}
              />
              <button type="submit" className="co-chat-send-btn">
                <FaPaperPlane />
              </button>
            </form>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}